/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TvNewsRouteImport } from './routes/tv-news'
import { Route as TvRouteImport } from './routes/tv'
import { Route as TrueCrimeRouteImport } from './routes/true-crime'
import { Route as SubscribeRouteImport } from './routes/subscribe'
import { Route as SearchRouteImport } from './routes/search'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostSlugRouteImport } from './routes/post.$slug'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminNewRouteImport } from './routes/_authenticated/admin.new'
import { Route as AuthenticatedAdminIngestionHealthRouteImport } from './routes/_authenticated/admin.ingestion-health'
import { Route as AuthenticatedAdminCoversRouteImport } from './routes/_authenticated/admin.covers'
import { Route as ApiPublicHooksIngestTvNewsRouteImport } from './routes/api/public/hooks/ingest-tv-news'
import { Route as AuthenticatedAdminIdEditRouteImport } from './routes/_authenticated/admin.$id.edit'

const TvNewsRoute = TvNewsRouteImport.update({
  id: '/tv-news',
  path: '/tv-news',
  getParentRoute: () => rootRouteImport,
} as any)
const TvRoute = TvRouteImport.update({
  id: '/tv',
  path: '/tv',
  getParentRoute: () => rootRouteImport,
} as any)
const TrueCrimeRoute = TrueCrimeRouteImport.update({
  id: '/true-crime',
  path: '/true-crime',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribeRoute = SubscribeRouteImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostSlugRoute = PostSlugRouteImport.update({
  id: '/post/$slug',
  path: '/post/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminNewRoute = AuthenticatedAdminNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminIngestionHealthRoute =
  AuthenticatedAdminIngestionHealthRouteImport.update({
    id: '/ingestion-health',
    path: '/ingestion-health',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCoversRoute =
  AuthenticatedAdminCoversRouteImport.update({
    id: '/covers',
    path: '/covers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicHooksIngestTvNewsRoute =
  ApiPublicHooksIngestTvNewsRouteImport.update({
    id: '/api/public/hooks/ingest-tv-news',
    path: '/api/public/hooks/ingest-tv-news',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminIdEditRoute =
  AuthenticatedAdminIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/search': typeof SearchRoute
  '/subscribe': typeof SubscribeRoute
  '/true-crime': typeof TrueCrimeRoute
  '/tv': typeof TvRoute
  '/tv-news': typeof TvNewsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/post/$slug': typeof PostSlugRoute
  '/admin/covers': typeof AuthenticatedAdminCoversRoute
  '/admin/ingestion-health': typeof AuthenticatedAdminIngestionHealthRoute
  '/admin/new': typeof AuthenticatedAdminNewRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/$id/edit': typeof AuthenticatedAdminIdEditRoute
  '/api/public/hooks/ingest-tv-news': typeof ApiPublicHooksIngestTvNewsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/search': typeof SearchRoute
  '/subscribe': typeof SubscribeRoute
  '/true-crime': typeof TrueCrimeRoute
  '/tv': typeof TvRoute
  '/tv-news': typeof TvNewsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/post/$slug': typeof PostSlugRoute
  '/admin/covers': typeof AuthenticatedAdminCoversRoute
  '/admin/ingestion-health': typeof AuthenticatedAdminIngestionHealthRoute
  '/admin/new': typeof AuthenticatedAdminNewRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/$id/edit': typeof AuthenticatedAdminIdEditRoute
  '/api/public/hooks/ingest-tv-news': typeof ApiPublicHooksIngestTvNewsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/search': typeof SearchRoute
  '/subscribe': typeof SubscribeRoute
  '/true-crime': typeof TrueCrimeRoute
  '/tv': typeof TvRoute
  '/tv-news': typeof TvNewsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/post/$slug': typeof PostSlugRoute
  '/_authenticated/admin/covers': typeof AuthenticatedAdminCoversRoute
  '/_authenticated/admin/ingestion-health': typeof AuthenticatedAdminIngestionHealthRoute
  '/_authenticated/admin/new': typeof AuthenticatedAdminNewRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/$id/edit': typeof AuthenticatedAdminIdEditRoute
  '/api/public/hooks/ingest-tv-news': typeof ApiPublicHooksIngestTvNewsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/search'
    | '/subscribe'
    | '/true-crime'
    | '/tv'
    | '/tv-news'
    | '/admin'
    | '/post/$slug'
    | '/admin/covers'
    | '/admin/ingestion-health'
    | '/admin/new'
    | '/admin/settings'
    | '/admin/$id/edit'
    | '/api/public/hooks/ingest-tv-news'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/search'
    | '/subscribe'
    | '/true-crime'
    | '/tv'
    | '/tv-news'
    | '/admin'
    | '/post/$slug'
    | '/admin/covers'
    | '/admin/ingestion-health'
    | '/admin/new'
    | '/admin/settings'
    | '/admin/$id/edit'
    | '/api/public/hooks/ingest-tv-news'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/search'
    | '/subscribe'
    | '/true-crime'
    | '/tv'
    | '/tv-news'
    | '/_authenticated/admin'
    | '/post/$slug'
    | '/_authenticated/admin/covers'
    | '/_authenticated/admin/ingestion-health'
    | '/_authenticated/admin/new'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/$id/edit'
    | '/api/public/hooks/ingest-tv-news'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  SearchRoute: typeof SearchRoute
  SubscribeRoute: typeof SubscribeRoute
  TrueCrimeRoute: typeof TrueCrimeRoute
  TvRoute: typeof TvRoute
  TvNewsRoute: typeof TvNewsRoute
  PostSlugRoute: typeof PostSlugRoute
  ApiPublicHooksIngestTvNewsRoute: typeof ApiPublicHooksIngestTvNewsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tv-news': {
      id: '/tv-news'
      path: '/tv-news'
      fullPath: '/tv-news'
      preLoaderRoute: typeof TvNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv': {
      id: '/tv'
      path: '/tv'
      fullPath: '/tv'
      preLoaderRoute: typeof TvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/true-crime': {
      id: '/true-crime'
      path: '/true-crime'
      fullPath: '/true-crime'
      preLoaderRoute: typeof TrueCrimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribe': {
      id: '/subscribe'
      path: '/subscribe'
      fullPath: '/subscribe'
      preLoaderRoute: typeof SubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/$slug': {
      id: '/post/$slug'
      path: '/post/$slug'
      fullPath: '/post/$slug'
      preLoaderRoute: typeof PostSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/new': {
      id: '/_authenticated/admin/new'
      path: '/new'
      fullPath: '/admin/new'
      preLoaderRoute: typeof AuthenticatedAdminNewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ingestion-health': {
      id: '/_authenticated/admin/ingestion-health'
      path: '/ingestion-health'
      fullPath: '/admin/ingestion-health'
      preLoaderRoute: typeof AuthenticatedAdminIngestionHealthRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/covers': {
      id: '/_authenticated/admin/covers'
      path: '/covers'
      fullPath: '/admin/covers'
      preLoaderRoute: typeof AuthenticatedAdminCoversRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/hooks/ingest-tv-news': {
      id: '/api/public/hooks/ingest-tv-news'
      path: '/api/public/hooks/ingest-tv-news'
      fullPath: '/api/public/hooks/ingest-tv-news'
      preLoaderRoute: typeof ApiPublicHooksIngestTvNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/$id/edit': {
      id: '/_authenticated/admin/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/$id/edit'
      preLoaderRoute: typeof AuthenticatedAdminIdEditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminCoversRoute: typeof AuthenticatedAdminCoversRoute
  AuthenticatedAdminIngestionHealthRoute: typeof AuthenticatedAdminIngestionHealthRoute
  AuthenticatedAdminNewRoute: typeof AuthenticatedAdminNewRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminIdEditRoute: typeof AuthenticatedAdminIdEditRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminCoversRoute: AuthenticatedAdminCoversRoute,
  AuthenticatedAdminIngestionHealthRoute:
    AuthenticatedAdminIngestionHealthRoute,
  AuthenticatedAdminNewRoute: AuthenticatedAdminNewRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminIdEditRoute: AuthenticatedAdminIdEditRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  SearchRoute: SearchRoute,
  SubscribeRoute: SubscribeRoute,
  TrueCrimeRoute: TrueCrimeRoute,
  TvRoute: TvRoute,
  TvNewsRoute: TvNewsRoute,
  PostSlugRoute: PostSlugRoute,
  ApiPublicHooksIngestTvNewsRoute: ApiPublicHooksIngestTvNewsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
