/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TvNewsRouteImport } from './routes/tv-news'
import { Route as TvRouteImport } from './routes/tv'
import { Route as TrueCrimeRouteImport } from './routes/true-crime'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShellRouteImport } from './routes/shell'
import { Route as SearchRouteImport } from './routes/search'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TagTagRouteImport } from './routes/tag.$tag'
import { Route as PostSlugRouteImport } from './routes/post.$slug'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as ApiPublicTmdb_lookupRouteImport } from './routes/api/public/_tmdb_lookup'
import { Route as AuthenticatedAdminTagsRouteImport } from './routes/_authenticated/admin.tags'
import { Route as AuthenticatedAdminStreamRouteImport } from './routes/_authenticated/admin.stream'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminRecommendationsRouteImport } from './routes/_authenticated/admin.recommendations'
import { Route as AuthenticatedAdminNewRouteImport } from './routes/_authenticated/admin.new'
import { Route as AuthenticatedAdminIdEditRouteImport } from './routes/_authenticated/admin.$id.edit'

const TvNewsRoute = TvNewsRouteImport.update({
  id: '/tv-news',
  path: '/tv-news',
  getParentRoute: () => rootRouteImport,
} as any)
const TvRoute = TvRouteImport.update({
  id: '/tv',
  path: '/tv',
  getParentRoute: () => rootRouteImport,
} as any)
const TrueCrimeRoute = TrueCrimeRouteImport.update({
  id: '/true-crime',
  path: '/true-crime',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/shell',
  path: '/shell',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TagTagRoute = TagTagRouteImport.update({
  id: '/tag/$tag',
  path: '/tag/$tag',
  getParentRoute: () => rootRouteImport,
} as any)
const PostSlugRoute = PostSlugRouteImport.update({
  id: '/post/$slug',
  path: '/post/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiPublicTmdb_lookupRoute = ApiPublicTmdb_lookupRouteImport.update({
  id: '/api/public/_tmdb_lookup',
  path: '/api/public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminTagsRoute = AuthenticatedAdminTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminStreamRoute =
  AuthenticatedAdminStreamRouteImport.update({
    id: '/stream',
    path: '/stream',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRecommendationsRoute =
  AuthenticatedAdminRecommendationsRouteImport.update({
    id: '/recommendations',
    path: '/recommendations',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminNewRoute = AuthenticatedAdminNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminIdEditRoute =
  AuthenticatedAdminIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/search': typeof SearchRoute
  '/shell': typeof ShellRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/true-crime': typeof TrueCrimeRoute
  '/tv': typeof TvRoute
  '/tv-news': typeof TvNewsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/post/$slug': typeof PostSlugRoute
  '/tag/$tag': typeof TagTagRoute
  '/admin/new': typeof AuthenticatedAdminNewRoute
  '/admin/recommendations': typeof AuthenticatedAdminRecommendationsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/stream': typeof AuthenticatedAdminStreamRoute
  '/admin/tags': typeof AuthenticatedAdminTagsRoute
  '/api/public': typeof ApiPublicTmdb_lookupRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/$id/edit': typeof AuthenticatedAdminIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/search': typeof SearchRoute
  '/shell': typeof ShellRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/true-crime': typeof TrueCrimeRoute
  '/tv': typeof TvRoute
  '/tv-news': typeof TvNewsRoute
  '/post/$slug': typeof PostSlugRoute
  '/tag/$tag': typeof TagTagRoute
  '/admin/new': typeof AuthenticatedAdminNewRoute
  '/admin/recommendations': typeof AuthenticatedAdminRecommendationsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/stream': typeof AuthenticatedAdminStreamRoute
  '/admin/tags': typeof AuthenticatedAdminTagsRoute
  '/api/public': typeof ApiPublicTmdb_lookupRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/$id/edit': typeof AuthenticatedAdminIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/search': typeof SearchRoute
  '/shell': typeof ShellRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/true-crime': typeof TrueCrimeRoute
  '/tv': typeof TvRoute
  '/tv-news': typeof TvNewsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/post/$slug': typeof PostSlugRoute
  '/tag/$tag': typeof TagTagRoute
  '/_authenticated/admin/new': typeof AuthenticatedAdminNewRoute
  '/_authenticated/admin/recommendations': typeof AuthenticatedAdminRecommendationsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/stream': typeof AuthenticatedAdminStreamRoute
  '/_authenticated/admin/tags': typeof AuthenticatedAdminTagsRoute
  '/api/public/_tmdb_lookup': typeof ApiPublicTmdb_lookupRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/$id/edit': typeof AuthenticatedAdminIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/search'
    | '/shell'
    | '/sitemap.xml'
    | '/true-crime'
    | '/tv'
    | '/tv-news'
    | '/admin'
    | '/post/$slug'
    | '/tag/$tag'
    | '/admin/new'
    | '/admin/recommendations'
    | '/admin/settings'
    | '/admin/stream'
    | '/admin/tags'
    | '/api/public'
    | '/admin/'
    | '/admin/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/search'
    | '/shell'
    | '/sitemap.xml'
    | '/true-crime'
    | '/tv'
    | '/tv-news'
    | '/post/$slug'
    | '/tag/$tag'
    | '/admin/new'
    | '/admin/recommendations'
    | '/admin/settings'
    | '/admin/stream'
    | '/admin/tags'
    | '/api/public'
    | '/admin'
    | '/admin/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/search'
    | '/shell'
    | '/sitemap.xml'
    | '/true-crime'
    | '/tv'
    | '/tv-news'
    | '/_authenticated/admin'
    | '/post/$slug'
    | '/tag/$tag'
    | '/_authenticated/admin/new'
    | '/_authenticated/admin/recommendations'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/stream'
    | '/_authenticated/admin/tags'
    | '/api/public/_tmdb_lookup'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  SearchRoute: typeof SearchRoute
  ShellRoute: typeof ShellRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TrueCrimeRoute: typeof TrueCrimeRoute
  TvRoute: typeof TvRoute
  TvNewsRoute: typeof TvNewsRoute
  PostSlugRoute: typeof PostSlugRoute
  TagTagRoute: typeof TagTagRoute
  ApiPublicTmdb_lookupRoute: typeof ApiPublicTmdb_lookupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tv-news': {
      id: '/tv-news'
      path: '/tv-news'
      fullPath: '/tv-news'
      preLoaderRoute: typeof TvNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv': {
      id: '/tv'
      path: '/tv'
      fullPath: '/tv'
      preLoaderRoute: typeof TvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/true-crime': {
      id: '/true-crime'
      path: '/true-crime'
      fullPath: '/true-crime'
      preLoaderRoute: typeof TrueCrimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shell': {
      id: '/shell'
      path: '/shell'
      fullPath: '/shell'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tag/$tag': {
      id: '/tag/$tag'
      path: '/tag/$tag'
      fullPath: '/tag/$tag'
      preLoaderRoute: typeof TagTagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/$slug': {
      id: '/post/$slug'
      path: '/post/$slug'
      fullPath: '/post/$slug'
      preLoaderRoute: typeof PostSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/_tmdb_lookup': {
      id: '/api/public/_tmdb_lookup'
      path: '/api/public'
      fullPath: '/api/public'
      preLoaderRoute: typeof ApiPublicTmdb_lookupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/tags': {
      id: '/_authenticated/admin/tags'
      path: '/tags'
      fullPath: '/admin/tags'
      preLoaderRoute: typeof AuthenticatedAdminTagsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/stream': {
      id: '/_authenticated/admin/stream'
      path: '/stream'
      fullPath: '/admin/stream'
      preLoaderRoute: typeof AuthenticatedAdminStreamRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/recommendations': {
      id: '/_authenticated/admin/recommendations'
      path: '/recommendations'
      fullPath: '/admin/recommendations'
      preLoaderRoute: typeof AuthenticatedAdminRecommendationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/new': {
      id: '/_authenticated/admin/new'
      path: '/new'
      fullPath: '/admin/new'
      preLoaderRoute: typeof AuthenticatedAdminNewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/$id/edit': {
      id: '/_authenticated/admin/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/$id/edit'
      preLoaderRoute: typeof AuthenticatedAdminIdEditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminNewRoute: typeof AuthenticatedAdminNewRoute
  AuthenticatedAdminRecommendationsRoute: typeof AuthenticatedAdminRecommendationsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminStreamRoute: typeof AuthenticatedAdminStreamRoute
  AuthenticatedAdminTagsRoute: typeof AuthenticatedAdminTagsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminIdEditRoute: typeof AuthenticatedAdminIdEditRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminNewRoute: AuthenticatedAdminNewRoute,
  AuthenticatedAdminRecommendationsRoute:
    AuthenticatedAdminRecommendationsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminStreamRoute: AuthenticatedAdminStreamRoute,
  AuthenticatedAdminTagsRoute: AuthenticatedAdminTagsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminIdEditRoute: AuthenticatedAdminIdEditRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  SearchRoute: SearchRoute,
  ShellRoute: ShellRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TrueCrimeRoute: TrueCrimeRoute,
  TvRoute: TvRoute,
  TvNewsRoute: TvNewsRoute,
  PostSlugRoute: PostSlugRoute,
  TagTagRoute: TagTagRoute,
  ApiPublicTmdb_lookupRoute: ApiPublicTmdb_lookupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
